name: update pull body
on:
  pull_request:
    types: [opened, reopened]
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: prepare env
#       env:
#         GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        export TZ=Asia/Riyadh
        if [ ${{ github.repository }} == "SallaApp/dashboard-api-docs" ] ; then 
          echo "PROJECT_ID=$(echo "68673" )" >> $GITHUB_ENV
          echo "PROJECT_NAME=$(echo "merchant" )" >> $GITHUB_ENV
        elif [ ${{ github.repository }} == "SallaApp/store-api-docs" ] ; then 
           echo "PROJECT_ID=$(echo "68673" )" >> $GITHUB_ENV  
           echo "PROJECT_NAME=$(echo "store-api" )" >> $GITHUB_ENV
        elif [ ${{ github.repository }} == "SallaApp/DevelopersPortal-API-Docs" ] ; then 
          echo "PROJECT_ID=$(echo "6009571" )" >> $GITHUB_ENV
          echo "PROJECT_NAME=$(echo "developersportal-api-docs" )" >> $GITHUB_ENV
        fi
        echo "BRANCH=$(echo ${{ github.head_ref }} | sed 's|/|%252F|g' )"  >> $GITHUB_ENV
        echo "TIME=$(date '+%Y-%m-%d %H:%M')" >> $GITHUB_ENV
#       echo "$GITHUB_CONTEXT"
    - name: update-pull-request
      uses: AsasInnab/pr-body-action@v1
      with:
        body: |
            ### Stoplight Projects
            | Name | URL | Updated |
            | :--- | :------ | :------ |
            | **Doc** | [URL](https://salla.stoplight.io/docs/${{ env.PROJECT_NAME }}/branch/${{ env.BRANCH }}/) |  ${{ env.TIME }} |
            | **Mock Server** | [URL](https://stoplight.io/mocks/salla/${{ env.PROJECT_NAME }}:${{ env.BRANCH }}/${{ env.PROJECT_ID }}) |  ${{ env.TIME }} |
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
